#ifndef II_INCLUDE_H
#define II_INCLUDE_H
#include <iostream>
#include <QApplication>
#include <QDialog>
#include <QFile>
#include <QHostInfo>
#include <QList>
#include <QListWidget>
#include <QMainWindow>
#include <QMessageBox>
#include <QMenu>
#include <QMouseEvent>
#include <QNetworkAccessManager>
#include <QNetworkDatagram>
#include <QNetworkProxy>
#include <QNetworkReply>
#include <QObject>
#include <QPainter>
#include <QPrinter>
#include <QPrintDialog>
#include <QScrollBar>
//#include <QSerialPort> //VER36.1
#include <QSqlDatabase>
#include <QStandardItem>
#include <QStorageInfo>
#include <QTimer>
#include <QTcpSocket>
#include <QTcpServer>
#include <QtGui>
#include <QtSql>
#include <QUdpSocket>
#include <random>
#include <string.h>
#if W
#include <tchar.h>
#endif
#include <math.h>
#endif // II_INCLUDE_H
